### PR TITLE
Fixed some typos in shell templates

### PR DESCRIPTION
**Pull request by FilipBB**

### CODE REVIEW

**Comment by aloisdg** [comment]
Thank for catching it! Can you rename your commit to follow our conventions?

**Comment by FilipBB** [comment]
Sure, how do I find out what they are?

**Comment by aloisdg** [comment]
Everything should be on the [contribution](https://github.com/base16-builder/base16-builder/blob/master/contributing.md) file. Basically for commits,  we use [commitizen](https://github.com/commitizen/cz-cli). ;)

**Comment by FilipBB** [comment]
Ok, should I change the commit messages as well, or just the pull request? I will have to resubmit the pull request to change the commit messages

**Pull request closed without merging**
