### PR TITLE
Add Unikitty scheme

### PR DESCRIPTION
**Pull request by joshwlewis**
This is a vibrant, bright scheme that works well in both dark and light variants. 

light

dark

### CODE REVIEW

**Comment by aloisdg** [comment]
Nice theme! Did you create it?

**Comment by alexbooker** [comment]
Merged 👌

Thanks for the contribution.

**Comment by joshwlewis** [comment]
@aloisdg Yep, sure did. I have my own repo here: https://github.com/joshwlewis/base16-unikitty.

Thanks for bringing this in.

**Comment by aloisdg** [comment]
Great! You should make more 😄

**Pull request closed without merging**
