### PR TITLE
Add a final draft of Contributing.md. Fix #30

### LINKED ISSUE #30: Document the template convention
Templates need to adhere to a certain [convention](https://github.com/alexbooker/base16-builder/issues/19#issuecomment-180026062) before _base16-builder_ can detect them.

Whilst I believe that most contributors will be able to deduce this convention by looking at the [templates](https://github.com/alexbooker/base16-builder/tree/master/db/templates) directory, it would also be beneficial to formally document the convention.

Seeing as how this information is most relevant to contributors, I think [`contributing.md`](https://github.com/alexbooker/base16-builder/tree/master/db/templates) would be a natural home for the so-called specification.

### PR DESCRIPTION
**Pull request by aloisdg**
related to #30

### CODE REVIEW

**Comment by alexbooker** [comment]
I'll check this out when I have time this evening. Thanks.

**Comment by alexbooker** [comment]
I'll check this out properly tomorrow afternoon.

**Comment by aloisdg** [comment]
No problem. Take your time.

**Comment by alexbooker** [comment]
The guideline could very well already state this, but just in case I forget to check later:

I think sheme and template file names should be all lowercase. Do you agree?

**Comment by aloisdg** [comment]
@alexbooker Sure.

**Comment by aloisdg** [comment]
@alexbooker scheme and template file names MUST or SHOULD be all lowercase? I think you want to say MUST instead of SHOULD. Can you confirm?

Also, I quickly wrote a regex to check a scheme/template name:

    [a-z0-9.-]+

Regular expression visualization

[Debuggex Demo](https://www.debuggex.com/r/dcwFJQL3FYgGyRbY)

**Comment by alexbooker** [comment]
I wasn't too sure at the time but now I am. It **must** be lowercase. Thanks.

**Comment by aloisdg** [comment]
@alexbooker Done !

**Comment by alexbooker** [comment]
@aloisdg Thanks for this.

**Comment by aloisdg** [comment]
@alexbooker  you are welcome :)

**Comment by alexbooker** [comment]
@aloisdg I want to make some small changes:

- Grammar changes
- You don't strictly **have** to create an issue first. That being said, it is **recommended**.
- In my experience, contributors seldom read the `contributing.md`. Those who do probably wont read it all. It is for that reason that I want to put the most important information at the top. 
- I think I can make the headings a bit clearer with a TOC
- I think I can make the template specification a bit clearer with more examples
- I think I can make it all sound a bit more... welcoming.

**Comment by aloisdg** [comment]
I agree with all. Can you fix all odd point directly?

**Pull request merged**
