### PR TITLE
fix(db): Update old comments. Close #47

### LINKED ISSUE #47: Adapt header comment in template
Some templates start with a header comment like this one:

``` 
<%=
bla bla
%>
```

We have to convert it.

### PR DESCRIPTION
**Pull request by aloisdg**
I also updated some `\n`.

### CODE REVIEW

**Comment by alexbooker** [comment]
There was a merge conflict. Did I merge this correctly? Thanks.

**Comment by aloisdg** [comment]
How can I see the conflict on GitHub UI?

**Comment by alexbooker** [comment]
Can you please look in the [templates](https://github.com/base16-builder/base16-builder/tree/master/db/templates) folder and make sure the templates look like they should (i.e. did I apply your changes correctly?) Thanks

**Comment by aloisdg** [comment]
Conflict came from smartftp.you did the right merge.

**Pull request merged**
