### PR TITLE
feat(template): Add templates for the oomox GTK theme creator

### PR DESCRIPTION
**Pull request by Luke-Nukem**
Added templates for use with the [oomox](https://github.com/actionless/oomox) GTK theme creator. The
light variant is mostly greyscale, while the dark variant uses a little more colour; I'm unsure if
the colours are suitable, please chagne if needed.

### CODE REVIEW

**Comment by Luke-Nukem** [comment]
[Screenshot for reference. Eighties Dark theme](http://imgur.com/77CjiLw)

**Comment by aloisdg** [comment]
Nice. Thank you.

**Comment by alexbooker** [comment]
Awesome work, @Luke-Nukem -- thanks :smile:!

**Comment by alexbooker** [comment]
Released with [`1.2.0`](https://github.com/base16-builder/base16-builder/releases/tag/1.2.0) :+1:

**Pull request merged**
