### PR TITLE
codemirror: Sync updates from auduchinok/base16-builder

### PR DESCRIPTION
**Pull request by belak**
Includes changes by @idleberg 

I'm not personally familiar with these changes, I'm just porting them from the other other base16-builder.

### CODE REVIEW

**Comment by alexbooker** [comment]
Are you porting pull requests from `chriskempson/base16-builder`? If so, please link them as I would like to ask their authors for permission to use their work here (I see you're @-mentioning the authors but I would also like to see the original pull request, thanks!)

**Comment by belak** [comment]
I will do this for the rest of them. I don't believe there's a pull request from this one, but it comes from his repo. https://github.com/idleberg/base16-builder

**Comment by alexbooker** [comment]
I have to focus on some work but rest assured I'll take some time to review this later today. Thank you for your effort :smile: :+1:!

**Comment by alexbooker** [comment]
>  I'll take some time to review this later today. 

I am such a liar 😛 

Merged now though, thanks!

**Pull request closed without merging**
