### PR TITLE
docs(): Added issue template to help guide users through the issue ad…

### PR DESCRIPTION
**Pull request by CrashyBang**
…ding process

Added issue template to help guide users through the issue adding process and get us the information
we need to further debug the problem

### CODE REVIEW

**Comment by alexbooker** [comment]
Thank you very much for this pull request :smile:. 

Here are my initial thoughts:

1. I don't think we need a **Problems Summary** section. Maybe an **Additional comments** section at the bottom would work better?

2. The instructions (_"If any of the below sections do not apply to you feel free to ignore or remove them..."_) should be inside a comment. See the [React Router `ISSUE_TEMPLATE.md`](https://raw.githubusercontent.com/reactjs/react-router/master/ISSUE_TEMPLATE.md) for an example. 

3. I think the **Steps to reproduce** section should come before the **Actual** and **Expected** sections. It is more natural to read: _"This is what I did, this is what happened but this is what I expected to happen"_

4. **Expected** and **Actual** are a bit ambiguous. Perhaps **Expected behaviour** and **Actual behaviour** would be better headings?

5. I'm not sure we need the **Theme and template you are trying to compile as well as background** section because that information should be in **Steps to reproduce**. Also, I think you mean **brightness** not **background**.

Your commit summary is too long and it does not adhere to the [commit message convention](https://github.com/base16-builder/base16-builder/blob/master/contributing.md#writing-a-good-commit) but I can change that with a `rebase`. 

If you want to make these changes or debate them with me then :ok_hand:.

**Comment by alexbooker** [comment]
Hey @CrashyBang 😄

I merged this and made some updates. Please can I have your feedback?

**Comment by CrashyBang** [comment]
Hey @alexbooker,
sorry I meant to get into this but have been having some issue's with my home PC (clean booting tonight). Had a look over I like it you have made it much clearer and easier to follow :)

**Comment by alexbooker** [comment]
I'm sure you're just being polite but there's no need to apologize ☺️

Thanks for getting this going! Hopefully when your system is running smoothly you'll still be interested in helping with #96

**Comment by CrashyBang** [comment]
Hey @alexbooker, definitely, I am really looking forward to it :).

**Pull request closed without merging**
