### PR TITLE
Fix i3 templates

### PR DESCRIPTION
**Pull request by robphoenix**
Add clarity to i3 templates and color_degraded to i3status templates

### CODE REVIEW

**Comment by aloisdg** [comment]
Nice! Thank you

**Comment by robphoenix** [comment]
**bump** just wondering if this might get merged?

**Comment by aloisdg** [comment]
Done!

**Comment by robphoenix** [comment]
Cool, you're very welcome!

**Comment by aloisdg** [comment]
Thank you again 👍

**Pull request merged**
