### PR TITLE
Feat(db): Add multiple colour schemes. Rewrite previous contribution (Oliveira).

### PR DESCRIPTION
**Pull request by protesilaos**
I am contributing my entire collection of colour schemes ([repo here](https://github.com/protesilaos/protesilaos.github.io) // [website here](http://www.protesilaos.com/schemes/)). 

I also made several changes to my previous contribution from a few months back (the Oliveira scheme).

I remain at your disposal for any further edits, corrections, etc. 

Thank you!

### CODE REVIEW

**Comment by aloisdg** [comment]
This is a huge PR! Thank you for your work!

I wonder whether we should call then protesilaos-* (where * is the current name). It would fit with atelier-*.

What do you think?

**Comment by protesilaos** [comment]
You are welcome! It is huge indeed. Take as much time as you need. Apologies for that.

On your suggestion. The "canonical" names are as I included them. However, I am internally grouping them under the tag "prot16" (which I explain is a play on my nickname and base16). So it could be prot16-*

I see one potential problem though and would like your feedback. It can create confusion when inserting a command (base16-builder -s prot16-* ... ). 

If you think that could be an issue, then I suggest we go with prot-*.

**Comment by alexbooker** [comment]
@protesilaos Thanks for this awesome pull request 🙏. @aloisdg, can you merge it?

Also, @aloisdg, I would rather one cannonical theme. If the name is taken, I think we should use another name.

**Comment by protesilaos** [comment]
Hello! Just to note that I can revise the PR if need be. I am fine with any further suggestion or guideline you may have.

**Comment by protesilaos** [comment]
I just noticed issue #126. Apologies for not seeing it in advance. Keeping things separate is the better approach. I am therefore closing this PR until further notice. Wish you all the best.

**Pull request closed without merging**
