### PR TITLE
fix(db): Fix zathura dark template

### PR DESCRIPTION
**Pull request by aleprovencio**

### CODE REVIEW

**Comment by alexbooker** [comment]
Awesome. Thanks very much.

**Comment by alexbooker** [comment]
You won't see your name under [contributors](https://github.com/base16-builder/base16-builder/graphs/contributors) because your local Git `user` config does not match your GitHub profile.

Is "alexandre@n37.com.br" the email you use to login to github.com?

If it isn't, what email do you use? I'll `git commit --amend` the commit so you get proper credit.

If it is, then I think you need to set your GitHub profile name to "Alexandre Provencio".

**Comment by aleprovencio** [comment]
That email is from a side job, not the correct one I'm sorry. Just updated github's profile name, thanks for pointing that out.

**Comment by alexbooker** [comment]
@aleprovencio What email do you use to login to GitHub? I can update the commit so you get the credit you deserve.

**Comment by aleprovencio** [comment]
That is `alexandreprovencio@gmail.com`, thank you @alexbooker

**Comment by alexbooker** [comment]
When I wrote that message, I was planning to do a simple `git commit --amend`. Because commits have been made since yours, I'll have to see if I can do this with a `rebase`. I'm not sure if I can, but I'll try :smile:

**Comment by alexbooker** [comment]
@aleprovencio Done :smile:

**Pull request merged**
