### PR TITLE
feat(HTML Preview): Improved the schemes preview HTML page

### PR DESCRIPTION
**Pull request by ClaytonPassmore**
Improved the HTML page where you preview schemes.
I tried to draw some inspiration from the mock design.

Affects #96. Probably doesn't close it though.
Saw this on Reddit today, figured I could help out.

Here's a preview:
ls_schemes

### CODE REVIEW

**Comment by ClaytonPassmore** [comment]
Hey @alexbooker, you seem important

**Comment by alexbooker** [comment]
Hi @ClaytonPassmore 

Thank you for the contribution :100: 

I have merged your changes and published `1.1.0` to npm

**Comment by aloisdg** [comment]
Nice render!

I think it could be better in two lines. 2x8 instead of 1x8. What do you think?

**Comment by alexbooker** [comment]
Did you mean 1x16?

**Comment by aloisdg** [comment]
Indeed. Fixed it. Thank you :)

**Comment by alexbooker** [comment]
I like 1x16 more...

**Comment by aloisdg** [comment]
I find the 2x8 layout more natural. When you look at the [solarized's 2x8 layout](http://ethanschoonover.com/solarized), it feels clear, simple and beautiful. At least, I find it like this. It is not a big use overwhole 😄

**Comment by alexbooker** [comment]
I guess it makes sense. I'm not too fuss really 😜

**Comment by aloisdg** [comment]
Me either. @ClaytonPassmore what do you think? :)

**Comment by ClaytonPassmore** [comment]
@alexbooker @aloisdg Yeah I think 2x8 could be nicer.
Actually, what might look good is to keep it 1x16 but have a visual break between the two sets of colors.

**Comment by aloisdg** [comment]
Ok. Can you try it? Thank you for your time involved :)

**Comment by ClaytonPassmore** [comment]
@aloisdg sure thing! No problem, happy to help :+1:

**Pull request closed without merging**
