### PR TITLE
feat(db): Add Wox support. Close #59

### LINKED ISSUE #59: Add Wox template
Hello,

Wox is an effective launcher for Windows. You can learn more about the project on its [repository](https://github.com/Wox-launcher/Wox).

Right now, I have the support for the dark and the light template (here with the solarized scheme):

dark

light

I created them with wox's [theme builder](http://www.getwox.com/theme/builder) with inspiration from Alfred ([1](http://www.alfredforum.com/topic/455-solarized-dark/) [2](https://github.com/imkmf/alfred-solarized) [3](https://github.com/timbuchwaldt/alfred-solarized) [4](http://www.chadkouse.com/2013/03/solarized-theme-for-alfred-v2.html)). I chose `0A` as accent color but any accent color will fit (I found `0C` really convenient too).

### PR DESCRIPTION
**Pull request by aloisdg**
Please discuss about the implementation in #59.

The accent color can be freely change.

### CODE REVIEW

**Comment by alexbooker** [comment]
I don't have Windows installed to test this. If you think it's ready to merge, please merge it. Thank you.

**Comment by aloisdg** [comment]
I would love a comment from the wox project before. If they dont answer, I will merge it. We can still improve it later.

**Comment by alexbooker** [comment]
@aloisdg Sounds good.

**Comment by alexbooker** [comment]
Any news from the Wox team?

**Comment by aloisdg** [comment]
As far as I know, no.

**Comment by alexbooker** [comment]
@aloisdg Ready to merge this yet? :wink:

**Comment by aloisdg** [comment]
@alexbooker wox templates are nunjucks syntax templates. An update is needed. Yesterday, I got my computer back and I am on my way to Paris from Bangalore. I will start again working here soon. 😏

**Comment by alexbooker** [comment]
@asessa Yay :tada:

**Comment by alexbooker** [comment]
About time :wink: 

Nice work, @aloisdg !!

**Comment by aloisdg** [comment]
:smile:

**Pull request merged**
